#!/bin/bash
set -e
VERSION=$(jq -r .version package.json)
VERSION_TAG=$VERSION.b$CIRCLE_BUILD_NUM

export DOCKER_BUILDKIT=1
export COMPOSE_DOCKER_CLI_BUILD=1

: "${GOOGLE_PROJECT_ID:?GOOGLE_PROJECT_ID must be set in CircleCI project settings}"
: "${GCLOUD_SERVICE_KEY:?GCLOUD_SERVICE_KEY must be set in CircleCI project settings}"

REGISTRY="us-docker.pkg.dev/${GOOGLE_PROJECT_ID}/peach-docker"
IMAGE="${REGISTRY}/redash"

echo -n "${GCLOUD_SERVICE_KEY}" | base64 --decode | docker login -u _json_key --password-stdin us-docker.pkg.dev

if [ $CIRCLE_BRANCH = master ] || [ $CIRCLE_BRANCH = preview-image ]
then
    docker build --build-arg skip_dev_deps=true -t "${IMAGE}:preview" -t "${IMAGE}:${VERSION_TAG}" .
    docker push "${IMAGE}:preview"
    docker push "${IMAGE}:${VERSION_TAG}"
else
    docker build --build-arg skip_dev_deps=true -t "${IMAGE}:${VERSION_TAG}" .
    docker push "${IMAGE}:${VERSION_TAG}"
fi

echo "Built: ${IMAGE}:${VERSION_TAG}"
