#!/bin/bash
set -e
VERSION=$(jq -r .version package.json)
VERSION_TAG=$VERSION.b$CIRCLE_BUILD_NUM

export DOCKER_BUILDKIT=1
export COMPOSE_DOCKER_CLI_BUILD=1

: "${DOCKER_REPOSITORY:?DOCKER_REPOSITORY env var must be set in CircleCI project settings}"

docker login -u $DOCKER_USER -p $DOCKER_PASS

if [ $CIRCLE_BRANCH = master ] || [ $CIRCLE_BRANCH = preview-image ]
then
    docker build --build-arg skip_dev_deps=true -t $DOCKER_REPOSITORY/redash:preview -t $DOCKER_REPOSITORY/preview:$VERSION_TAG .
    docker push $DOCKER_REPOSITORY/redash:preview
    docker push $DOCKER_REPOSITORY/preview:$VERSION_TAG
else
    docker build --build-arg skip_dev_deps=true -t $DOCKER_REPOSITORY/redash:$VERSION_TAG .
    docker push $DOCKER_REPOSITORY/redash:$VERSION_TAG
fi

echo "Built: $VERSION_TAG"
