#!/bin/bash

if [ "${GITHUB_REPOSITORY}" != "peachfinance/redash" ]; then
	echo "Skipping image build, as this isn't the peachfinance/redash repository"
	exit 0
fi

if [ "${GITHUB_REF_NAME}" != "master" ] && [ "${GITHUB_REF_NAME}" != "preview-image" ]; then
	echo "Skipping image build, as this isn't the 'master' nor 'preview-image' branch"
	exit 0
fi

if [ "x${GOOGLE_PROJECT_ID}" = "x" ] || [ "x${DOCKER_PASS}" = "x" ]; then
	echo "Skipping image build, as the login details aren't available"
	exit 0
fi

set -e
VERSION=$(jq -r .version package.json)
VERSION_TAG="$VERSION.b${GITHUB_RUN_ID}.${GITHUB_RUN_NUMBER}"

export DOCKER_BUILDKIT=1
export COMPOSE_DOCKER_CLI_BUILD=1

REGISTRY="us-docker.pkg.dev/${GOOGLE_PROJECT_ID}/peach-docker"
IMAGE="${REGISTRY}/redash"

echo "${DOCKER_PASS}" | docker login -u _json_key --password-stdin us-docker.pkg.dev

DOCKER_TAGS="-t ${IMAGE}:preview -t ${IMAGE}:${VERSION_TAG}"

docker build --build-arg install_groups="main,all_ds,dev" ${DOCKER_TAGS} .

docker push "${IMAGE}:preview"
docker push "${IMAGE}:${VERSION_TAG}"

echo "Built: ${IMAGE}:${VERSION_TAG}"
